// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:50d13c26-788f-4923-9a78-7a71f7e4f8c8",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Rp64pqhSu",
    "aws_user_pools_web_client_id": "5ekjld7sigi5v9k9utjqj7pcl4"
};


export default awsmobile;
